name: "Build"
on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: silvenga-docker/build-image@latest
      with:
        workingPath: ./nginx
        dockerUserName: silvenga-docker
        dockerPassword: ${{ secrets.GITHUB_TOKEN }}
        dockerImageName: ${{ github.repository }}/nginx
        dockerTags: latest,${{ github.sha }}
    - uses: silvenga-docker/build-image@latest
      with:
        workingPath: ./php-fpm
        dockerUserName: silvenga-docker
        dockerPassword: ${{ secrets.GITHUB_TOKEN }}
        dockerImageName: ${{ github.repository }}/php-fpm
        dockerTags: latest,${{ github.sha }}
