name: "Build"
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: silvenga-docker/build-image@latest
      with:
        workingPath: ./nginx
        dockerRegistery: ghcr.io
        dockerUserName: ${{ secrets.GHCR_USER }}
        dockerPassword: ${{ secrets.GHCR_PAT }}
        dockerImageName: ${{ github.repository }}/nginx
        dockerTags: latest,${{ github.sha }}
    - uses: silvenga-docker/build-image@latest
      with:
        workingPath: ./php-fpm
        dockerRegistery: ghcr.io
        dockerUserName: ${{ secrets.GHCR_USER }}
        dockerPassword: ${{ secrets.GHCR_PAT }}
        dockerImageName: ${{ github.repository }}/php-fpm
        dockerTags: latest,${{ github.sha }}
